# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 1 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    environment: YOUTH
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: |
          env
