  
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth2_read

on:
  workflow_dispatch:
  schedule:
     - cron: '10 0-12/3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    environment: YOUTH2
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ1: ${{ secrets.YOUTH_READ1 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ5 }}
    steps:
      - uses: actions/checkout@v1

      - name: Clone
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
          
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: |
          cd ~/Scripts
          npm install
          
      - name: 'Run youth_read1'
        if: env.YOUTH_READ1
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ1 }}

      - name: 'Run youth_read2'
        if: env.YOUTH_READ2
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          
      - name: 'Run youth_read3'
        if: env.YOUTH_READ3
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          
      - name: 'Run youth_read4'
        if: env.YOUTH_READ4
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}

      - name: 'Run youth_read5'
        if: env.YOUTH_READ5
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ5 }}
